from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("日志检测系统")
        Form.resize(819, 800)
        Form.setMinimumSize(QtCore.QSize(800, 300))
        Form.setMaximumSize(QtCore.QSize(80000, 60000))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")

        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.save_button.setFixedSize(self.save_button.sizeHint().width() * 2, self.save_button.sizeHint().height() * 2)
        self.verticalLayout.addWidget(self.save_button, 0, QtCore.Qt.AlignRight)

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(30, 30))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.login_record_widget = QtWidgets.QWidget(Form)
        self.login_record_layout = QtWidgets.QHBoxLayout(self.login_record_widget)
        self.label_4 = QtWidgets.QLabel(self.login_record_widget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setObjectName("label_4")
        self.login_record_layout.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.login_record_widget)

        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget_2)

        self.exception_example_widget = QtWidgets.QWidget(Form)
        self.exception_example_layout = QtWidgets.QHBoxLayout(self.exception_example_widget)
        self.label_6 = QtWidgets.QLabel(self.exception_example_widget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setObjectName("label_6")
        self.exception_example_layout.addWidget(self.label_6)
        self.verticalLayout.addWidget(self.exception_example_widget)

        self.tableWidget_3 = QtWidgets.QTableWidget(Form)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.tableWidget_3)

        self.abnormal_login_widget = QtWidgets.QWidget(Form)
        self.abnormal_login_layout = QtWidgets.QHBoxLayout(self.abnormal_login_widget)
        self.label_5 = QtWidgets.QLabel(self.abnormal_login_widget)
        self.label_5.setObjectName("label_5")
        self.abnormal_login_layout.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.abnormal_login_widget)

        self.tableWidget_5 = QtWidgets.QTableWidget(Form)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget_5)

        self.auth_log_widget = QtWidgets.QWidget(Form)
        self.auth_log_layout = QtWidgets.QHBoxLayout(self.auth_log_widget)
        self.label_7 = QtWidgets.QLabel(self.auth_log_widget)
        self.label_7.setObjectName("label_7")
        self.auth_log_layout.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.auth_log_widget)

        self.tableWidget_6 = QtWidgets.QTableWidget(Form)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget_6)

        self.monitor_widget = QtWidgets.QWidget(Form)
        self.monitor_layout = QtWidgets.QHBoxLayout(self.monitor_widget)
        self.label_8 = QtWidgets.QLabel(self.monitor_widget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setObjectName("label_8")
        self.label_8.setText("实时监控和告警")
        self.monitor_layout.addWidget(self.label_8)
        self.verticalLayout.addWidget(self.monitor_widget)

        self.alert_log = QtWidgets.QTextEdit(Form)
        self.alert_log.setObjectName("alert_log")
        self.verticalLayout.addWidget(self.alert_log)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "日志检测系统"))
        self.save_button.setText(_translate("Form", "保存"))
        self.label.setText(_translate("Form", "CPU占比"))
        self.label_3.setText(_translate("Form", "内存使用占比"))
        self.label_2.setText(_translate("Form", "任务总数"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "进程"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "USER"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "PR"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "NI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "VIRT"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "RES"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "SHR"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "%CPU"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "%MEM"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "TIME+"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "COMMAND"))
        self.label_4.setText(_translate("Form", "登录记录"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "root"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "登陆状态"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "日期"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "登陆时间"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "IP"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "持续时间"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "状态"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "越权操作"))
        self.label_5.setText(_translate("Form", "异常登陆状况"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("Form", "用户名"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("Form", "登录形式"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("Form", "IP地址"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("Form", "时间日期"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("Form", "地理位置"))
        self.label_6.setText(_translate("Form", "异常示例"))
        self.label_7.setText(_translate("Form", "auth.log 记录"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("Form", "用户"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("Form", "事件"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("Form", "IP地址"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("Form", "地理位置"))
